import { OrgStructureData, OrgWorkCenter, OrgArea, OrgPosition, OrgUser } from "@/types/orgStructure";
import { OrganizationPreferences } from "@/types/preferences";
import { IperMatrixItem } from "@/app/dashboard/components/IperMatrixView";
import { ProgramActivity } from "@/types/preventiveProgram";

export const SERGIO_ORG_ID = "org_sergio";

export const SERGIO_CONSTRUCTION_PREFERENCES: OrganizationPreferences = {
  organizationName: "Constructora Horizonte SpA",
  organizationSize: "51-200",
  organizationSector: "Construcción",
  experienceLevel: "expert",
  guidanceLevel: "contextual",
  riskEvaluationMethod: "ds44",
  riskManagementApproach: "iper",
  modules: {
    miper: true,
    documentManagement: true,
    aprVirtual: true,
  },
  onboardingCompleted: true,
  onboardingCompletedAt: "2026-01-10T09:00:00.000Z",
  onboardingStep: 5,
  tourCompleted: true,
  moduleConfigurations: {
    miper: {
      configured: true,
      methodology: "dynamic5x5_vep",
      confirmed: true,
      configuredAt: "2026-02-15T14:30:00.000Z",
    },
    preventivePlanning: {
      configured: true,
      hasExistingProgram: true,
      setupMode: "create_base",
      configuredAt: "2026-01-15T11:00:00.000Z",
    },
  },
};

export const SERGIO_WORK_CENTERS: OrgWorkCenter[] = [
  {
    id: "wc_santiago_corp",
    organizationId: SERGIO_ORG_ID,
    name: "Obra Edificio Corporativo Santiago",
    code: "OBRA-CS",
    description: "Torre corporativa de 24 pisos y 4 subterráneos en Las Condes.",
    address: "Av. Apoquindo 4800, Las Condes, Santiago",
    status: "Activo",
  },
  {
    id: "wc_biobio_hospital",
    organizationId: SERGIO_ORG_ID,
    name: "Obra Hospital Regional Biobío",
    code: "OBRA-HB",
    description: "Complejo hospitalario de alta complejidad de 85.000 m² en Concepción.",
    address: "Av. San Juan Bosco 1200, Concepción, Región del Biobío",
    status: "Activo",
  },
  {
    id: "wc_parque_norte",
    organizationId: SERGIO_ORG_ID,
    name: "Obra Condominio Parque Norte",
    code: "OBRA-PN",
    description: "Desarrollo habitacional de 6 edificios de 12 pisos con áreas comunes y subterráneos.",
    address: "Camino del Parque 1500, Chicureo, Colina",
    status: "Activo",
  },
];

export const SERGIO_POSITIONS: OrgPosition[] = [
  {
    id: "pos_admin_obra",
    organizationId: SERGIO_ORG_ID,
    name: "Administrador de Obra",
    code: "ADM-01",
    description: "Liderazgo integral técnico, contractual y operativo de faena.",
    status: "Activo",
    totalStaff: 3,
    menCount: 2,
    womenCount: 1,
    otherCount: 0,
    specialConditionsNote: "",
  },
  {
    id: "pos_jefe_terreno",
    organizationId: SERGIO_ORG_ID,
    name: "Jefe de Terreno",
    code: "TER-02",
    description: "Coordinación directa de frentes de trabajo y cuadrillas en obra.",
    status: "Activo",
    totalStaff: 4,
    menCount: 3,
    womenCount: 1,
    otherCount: 0,
    specialConditionsNote: "",
  },
  {
    id: "pos_prevencionista",
    organizationId: SERGIO_ORG_ID,
    name: "Prevencionista de Riesgos",
    code: "PR-03",
    description: "Gestión técnica de prevención, cumplimiento DS 44 y control en terreno.",
    status: "Activo",
    totalStaff: 3,
    menCount: 1,
    womenCount: 2,
    otherCount: 0,
    specialConditionsNote: "",
  },
  {
    id: "pos_supervisor",
    organizationId: SERGIO_ORG_ID,
    name: "Supervisor",
    code: "SUP-04",
    description: "Supervisión de calidad, avance y seguridad de frentes específicos.",
    status: "Activo",
    totalStaff: 6,
    menCount: 5,
    womenCount: 1,
    otherCount: 0,
    specialConditionsNote: "",
  },
  {
    id: "pos_capataz",
    organizationId: SERGIO_ORG_ID,
    name: "Capataz",
    code: "CAP-05",
    description: "Mando directo de cuadrillas de obra gruesa y terminaciones.",
    status: "Activo",
    totalStaff: 8,
    menCount: 8,
    womenCount: 0,
    otherCount: 0,
    specialConditionsNote: "",
  },
  {
    id: "pos_maestro_primera",
    organizationId: SERGIO_ORG_ID,
    name: "Maestro Primera",
    code: "MP-06",
    description: "Ejecución calificada de enfierradura, moldajes, albañilería y terminaciones.",
    status: "Activo",
    totalStaff: 25,
    menCount: 22,
    womenCount: 3,
    otherCount: 0,
    specialConditionsNote: "Trabajo en altura física",
  },
  {
    id: "pos_maestro_segunda",
    organizationId: SERGIO_ORG_ID,
    name: "Maestro Segunda",
    code: "MS-07",
    description: "Apoyo a maestros de primera en tareas de construcción y montaje.",
    status: "Activo",
    totalStaff: 20,
    menCount: 18,
    womenCount: 2,
    otherCount: 0,
    specialConditionsNote: "",
  },
  {
    id: "pos_jornal",
    organizationId: SERGIO_ORG_ID,
    name: "Jornal",
    code: "JOR-08",
    description: "Aseo, acarreo de materiales, orden de frentes de faena y apoyo general.",
    status: "Activo",
    totalStaff: 35,
    menCount: 30,
    womenCount: 5,
    otherCount: 0,
    specialConditionsNote: "Manipulación manual de cargas",
  },
  {
    id: "pos_operador_maquinaria",
    organizationId: SERGIO_ORG_ID,
    name: "Operador de Maquinaria",
    code: "OPM-09",
    description: "Operación de retroexcavadoras, grúas torre y minicargadores.",
    status: "Activo",
    totalStaff: 6,
    menCount: 6,
    womenCount: 0,
    otherCount: 0,
    specialConditionsNote: "Operador con licencia D",
  },
  {
    id: "pos_electricista",
    organizationId: SERGIO_ORG_ID,
    name: "Electricista",
    code: "ELE-10",
    description: "Instalación de faenas provisorias, tableros TDF y redes eléctricas.",
    status: "Activo",
    totalStaff: 8,
    menCount: 7,
    womenCount: 1,
    otherCount: 0,
    specialConditionsNote: "Certificación SEC",
  },
  {
    id: "pos_gasfiter",
    organizationId: SERGIO_ORG_ID,
    name: "Gasfíter",
    code: "GAS-11",
    description: "Instalaciones sanitarias, redes contra incendio y tuberías PPR/cobre.",
    status: "Activo",
    totalStaff: 5,
    menCount: 5,
    womenCount: 0,
    otherCount: 0,
    specialConditionsNote: "",
  },
  {
    id: "pos_bodeguero",
    organizationId: SERGIO_ORG_ID,
    name: "Bodeguero",
    code: "BOD-12",
    description: "Control de inventario, recepción de insumos y custodia de EPP.",
    status: "Activo",
    totalStaff: 4,
    menCount: 3,
    womenCount: 1,
    otherCount: 0,
    specialConditionsNote: "Manejo de sustancias peligrosas",
  },
  {
    id: "pos_admin_oficina",
    organizationId: SERGIO_ORG_ID,
    name: "Administrativo de Obra",
    code: "ADM-13",
    description: "Control de asistencia, remuneraciones, subcontratos y compras de faena.",
    status: "Activo",
    totalStaff: 5,
    menCount: 1,
    womenCount: 4,
    otherCount: 0,
    specialConditionsNote: "",
  },
];

export const SERGIO_AREAS: OrgArea[] = [
  // 1. Obra Edificio Corporativo Santiago
  {
    id: "area_cs_admin",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_santiago_corp",
    workCenterName: "Obra Edificio Corporativo Santiago",
    name: "Administración de Obra",
    description: "Dirección técnica y administrativa de la torre corporativa.",
    processes: [
      {
        id: "pr_cs_adm_1",
        organizationId: SERGIO_ORG_ID,
        name: "Gestión Documental y Permisos",
        description: "Tramitaciones municipales, recepción y contratos de obra.",
        subprocesses: [
          { id: "sub_cs_1", organizationId: SERGIO_ORG_ID, name: "Revisión de carpetas de subcontratos" },
        ],
      },
      {
        id: "pr_cs_adm_2",
        organizationId: SERGIO_ORG_ID,
        name: "Control de Calidad y Ensayos",
        description: "Ensayos de hormigón a compresión y control de densidades.",
        subprocesses: [],
      },
    ],
  },
  {
    id: "area_cs_construccion",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_santiago_corp",
    workCenterName: "Obra Edificio Corporativo Santiago",
    name: "Construcción",
    description: "Frentes de obra gruesa y estructura metálica principal.",
    processes: [
      {
        id: "pr_cs_cst_1",
        organizationId: SERGIO_ORG_ID,
        name: "Excavaciones Profundas",
        description: "Excavación masiva con entibación y anclajes en subterráneos.",
        subprocesses: [
          { id: "sub_cs_exc_1", organizationId: SERGIO_ORG_ID, name: "Instalación de pernos de anclaje" },
          { id: "sub_cs_exc_2", organizationId: SERGIO_ORG_ID, name: "Perfilado mecánico de taludes" },
        ],
      },
      {
        id: "pr_cs_cst_2",
        organizationId: SERGIO_ORG_ID,
        name: "Enfierradura Estructural",
        description: "Doblado, armado y colocación de armaduras en vigas y columnas.",
        subprocesses: [],
      },
      {
        id: "pr_cs_cst_3",
        organizationId: SERGIO_ORG_ID,
        name: "Montaje de Moldajes",
        description: "Colocación y afianzamiento de moldajes metálicos modulares.",
        subprocesses: [],
      },
      {
        id: "pr_cs_cst_4",
        organizationId: SERGIO_ORG_ID,
        name: "Hormigonado de Elementos Verticales y Losas",
        description: "Vaciado mediante bomba de hormigón y vibrado mecánico.",
        subprocesses: [],
      },
      {
        id: "pr_cs_cst_5",
        organizationId: SERGIO_ORG_ID,
        name: "Montaje Estructural a Mayor a 1.8m",
        description: "Montaje de vigas y losas prefabricadas con grúa torre a más de 15m.",
        subprocesses: [
          { id: "sub_cs_mnt_1", organizationId: SERGIO_ORG_ID, name: "Izaje con Grúa Torre" },
          { id: "sub_cs_mnt_2", organizationId: SERGIO_ORG_ID, name: "Fijación y soldadura en altura" },
        ],
      },
    ],
  },
  {
    id: "area_cs_prevencion",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_santiago_corp",
    workCenterName: "Obra Edificio Corporativo Santiago",
    name: "Prevención de Riesgos",
    description: "Departamento de Seguridad y Salud en el Trabajo en terreno.",
    processes: [
      {
        id: "pr_cs_prev_1",
        organizationId: SERGIO_ORG_ID,
        name: "Inspecciones de Seguridad en Altura",
        description: "Verificación de SPDC, mallas de protección perimetral y barandas.",
        subprocesses: [],
      },
      {
        id: "pr_cs_prev_2",
        organizationId: SERGIO_ORG_ID,
        name: "Supervisión de Bloqueos LOTO",
        description: "Control de energías peligrosas en maquinaria e instalaciones de faena.",
        subprocesses: [],
      },
    ],
  },
  {
    id: "area_cs_bodega",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_santiago_corp",
    workCenterName: "Obra Edificio Corporativo Santiago",
    name: "Bodega y Logística",
    description: "Acopio y abastecimiento de insumos, herramientas y EPP.",
    processes: [
      {
        id: "pr_cs_bod_1",
        organizationId: SERGIO_ORG_ID,
        name: "Recepción y Control de Materiales",
        description: "Descarga segura con grúa pluma y verificación de guías.",
        subprocesses: [],
      },
      {
        id: "pr_cs_bod_2",
        organizationId: SERGIO_ORG_ID,
        name: "Almacenamiento de Sustancias Peligrosas",
        description: "Custodia de desmoldantes, aditivos y solventes con cubeto de retención.",
        subprocesses: [],
      },
      {
        id: "pr_cs_bod_3",
        organizationId: SERGIO_ORG_ID,
        name: "Despacho Interno a Cuadrillas",
        description: "Entrega de EPP certificados y revisión periódica de herramientas eléctricas.",
        subprocesses: [],
      },
    ],
  },

  // 2. Obra Hospital Regional Biobío
  {
    id: "area_hb_admin",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_biobio_hospital",
    workCenterName: "Obra Hospital Regional Biobío",
    name: "Administración de Obra",
    description: "Oficina técnica y gerencia del proyecto hospitalario.",
    processes: [
      {
        id: "pr_hb_adm_1",
        organizationId: SERGIO_ORG_ID,
        name: "Planificación y Control de Avance",
        description: "Programación semanal de frentes hospitalarios en software BIM/Primavera.",
        subprocesses: [],
      },
      {
        id: "pr_hb_adm_2",
        organizationId: SERGIO_ORG_ID,
        name: "Coordinación Técnica de Especialidades",
        description: "Interferencias entre instalaciones sanitarias, eléctricas y gases clínicos.",
        subprocesses: [],
      },
    ],
  },
  {
    id: "area_hb_civiles",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_biobio_hospital",
    workCenterName: "Obra Hospital Regional Biobío",
    name: "Obras Civiles",
    description: "Fundaciones especiales, aisladores sísmicos y estructura de hormigón armado.",
    processes: [
      {
        id: "pr_hb_civ_1",
        organizationId: SERGIO_ORG_ID,
        name: "Excavaciones Masivas y Zanjas",
        description: "Zanjas de drenaje profundo y fundaciones para pabellones quirúrgicos.",
        subprocesses: [
          { id: "sub_hb_exc_1", organizationId: SERGIO_ORG_ID, name: "Apertura de Zanjas > 1.5m con entibación NCh 349" },
          { id: "sub_hb_exc_2", organizationId: SERGIO_ORG_ID, name: "Drenaje y agotamiento de napa freática" },
        ],
      },
      {
        id: "pr_hb_civ_2",
        organizationId: SERGIO_ORG_ID,
        name: "Hormigonado Masivo de Fundaciones",
        description: "Losa de fundación con control térmico y aditivos especiales.",
        subprocesses: [],
      },
      {
        id: "pr_hb_civ_3",
        organizationId: SERGIO_ORG_ID,
        name: "Instalación de Enfierraduras",
        description: "Enfierradura de alta densidad sísmica para muros de hormigón.",
        subprocesses: [],
      },
    ],
  },
  {
    id: "area_hb_instalaciones",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_biobio_hospital",
    workCenterName: "Obra Hospital Regional Biobío",
    name: "Instalaciones",
    description: "Redes críticas eléctricas, sanitarias y climatización hospitalaria.",
    processes: [
      {
        id: "pr_hb_ins_1",
        organizationId: SERGIO_ORG_ID,
        name: "Instalación Eléctrica Media y Baja Tensión",
        description: "Montaje de transformadores, tableros TDF 380V y grupos electrógenos.",
        subprocesses: [
          { id: "sub_hb_ins_1", organizationId: SERGIO_ORG_ID, name: "Canalizaciones subterráneas y bandejas porta-conductores" },
          { id: "sub_hb_ins_2", organizationId: SERGIO_ORG_ID, name: "Conexión y prueba de tableros TDF con bloqueo LOTO" },
        ],
      },
      {
        id: "pr_hb_ins_2",
        organizationId: SERGIO_ORG_ID,
        name: "Instalación Sanitaria y Redes Húmedas",
        description: "Red de agua potable, alcantarillado y sistema de extinción por rociadores.",
        subprocesses: [],
      },
      {
        id: "pr_hb_ins_3",
        organizationId: SERGIO_ORG_ID,
        name: "Climatización y Gases Clínicos",
        description: "Montaje de ductos de aire acondicionado y tuberías de oxígeno/vacío.",
        subprocesses: [],
      },
    ],
  },
  {
    id: "area_hb_prevencion",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_biobio_hospital",
    workCenterName: "Obra Hospital Regional Biobío",
    name: "Prevención de Riesgos",
    description: "Supervisión del cumplimiento de protocolos MINSAL y estándares de seguridad.",
    processes: [
      {
        id: "pr_hb_prev_1",
        organizationId: SERGIO_ORG_ID,
        name: "Gestión de Permisos de Trabajo Seguro (PTS)",
        description: "Emisión de permisos para trabajo en caliente, espacios confinados y excavaciones.",
        subprocesses: [],
      },
      {
        id: "pr_hb_prev_2",
        organizationId: SERGIO_ORG_ID,
        name: "Control de Protocolos de Vigilancia MINSAL",
        description: "Vigilancia de ruido ocupacional (PREXOR), sílice (PLANESI) y ergonomía (TMERT).",
        subprocesses: [],
      },
    ],
  },

  // 3. Obra Condominio Parque Norte
  {
    id: "area_pn_admin",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_parque_norte",
    workCenterName: "Obra Condominio Parque Norte",
    name: "Administración",
    description: "Gestión operativa y técnica de las 6 torres habitacionales.",
    processes: [
      {
        id: "pr_pn_adm_1",
        organizationId: SERGIO_ORG_ID,
        name: "Control Presupuestario de Faena",
        description: "Monitoreo de rendimientos de mano de obra y costos de subcontratos.",
        subprocesses: [],
      },
      {
        id: "pr_pn_adm_2",
        organizationId: SERGIO_ORG_ID,
        name: "Atención a Propietarios y Post-Venta",
        description: "Control de observaciones de entrega en torres terminadas.",
        subprocesses: [],
      },
    ],
  },
  {
    id: "area_pn_construccion",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_parque_norte",
    workCenterName: "Obra Condominio Parque Norte",
    name: "Construcción",
    description: "Obra gruesa de torres habitacionales y albañilerías.",
    processes: [
      {
        id: "pr_pn_cst_1",
        organizationId: SERGIO_ORG_ID,
        name: "Obra Gruesa",
        description: "Estructura de hormigón armado de 12 pisos por torre.",
        subprocesses: [],
      },
      {
        id: "pr_pn_cst_2",
        organizationId: SERGIO_ORG_ID,
        name: "Albañilería Armada",
        description: "Levantamiento de tabiques y muros divisorios de ladrillo cerámico.",
        subprocesses: [],
      },
      {
        id: "pr_pn_cst_3",
        organizationId: SERGIO_ORG_ID,
        name: "Techumbre e Impermeabilizaciones",
        description: "Membranas asfálticas y sellado de cubiertas en altura.",
        subprocesses: [],
      },
    ],
  },
  {
    id: "area_pn_terminaciones",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_parque_norte",
    workCenterName: "Obra Condominio Parque Norte",
    name: "Terminaciones",
    description: "Pinturas, revestimientos, pisos y carpintería de departamentos.",
    processes: [
      {
        id: "pr_pn_ter_1",
        organizationId: SERGIO_ORG_ID,
        name: "Pintura de Interiores y Fachadas",
        description: "Lijado, pasta muro y aplicación de pintura látex y esmaltes en departamentos y fachadas.",
        subprocesses: [
          { id: "sub_pn_ter_1", organizationId: SERGIO_ORG_ID, name: "Preparación de superficies y andamios" },
          { id: "sub_pn_ter_2", organizationId: SERGIO_ORG_ID, name: "Aplicación de pintura con rodillo y pistola airless" },
        ],
      },
      {
        id: "pr_pn_ter_2",
        organizationId: SERGIO_ORG_ID,
        name: "Instalación de Revestimientos Cerámicos y Porcelanato",
        description: "Corte de piezas con amoladora angular y pegado con adhesivos especiales.",
        subprocesses: [],
      },
      {
        id: "pr_pn_ter_3",
        organizationId: SERGIO_ORG_ID,
        name: "Carpintería y Montaje de Puertas y Ventanas",
        description: "Instalación de puertas de madera, ventanas de termopanel y molduras.",
        subprocesses: [],
      },
    ],
  },
  {
    id: "area_pn_prevencion",
    organizationId: SERGIO_ORG_ID,
    workCenterId: "wc_parque_norte",
    workCenterName: "Obra Condominio Parque Norte",
    name: "Prevención de Riesgos",
    description: "Inspecciones preventivas y charlas operativas en condominio.",
    processes: [
      {
        id: "pr_pn_prev_1",
        organizationId: SERGIO_ORG_ID,
        name: "Monitoreo de Ruido y Polvo (Planes DS 594)",
        description: "Mediciones ambientales y control de abatimiento de polvo en faena.",
        subprocesses: [],
      },
      {
        id: "pr_pn_prev_2",
        organizationId: SERGIO_ORG_ID,
        name: "Capacitación Diaria ODI en Terreno",
        description: "Charlas de 5 minutos al inicio de jornada con registros firmados.",
        subprocesses: [],
      },
    ],
  },
];

export const SERGIO_USERS: OrgUser[] = [
  {
    id: "user_sergio_jara",
    organizationId: SERGIO_ORG_ID,
    name: "Sergio Jara",
    email: "sergio.jara@safetyclub.cl",
    role: "Administrador",
    cargoId: "pos_admin_obra",
    status: "Activo",
  },
  {
    id: "user_camila_valenzuela",
    organizationId: SERGIO_ORG_ID,
    name: "Camila Valenzuela",
    email: "c.valenzuela@horizonte.cl",
    role: "Editor",
    cargoId: "pos_prevencionista",
    status: "Activo",
  },
  {
    id: "user_rodrigo_morales",
    organizationId: SERGIO_ORG_ID,
    name: "Rodrigo Morales",
    email: "r.morales@horizonte.cl",
    role: "Editor",
    cargoId: "pos_jefe_terreno",
    status: "Activo",
  },
  {
    id: "user_patricio_fuenzalida",
    organizationId: SERGIO_ORG_ID,
    name: "Patricio Fuenzalida",
    email: "p.fuenzalida@horizonte.cl",
    role: "Lector",
    cargoId: "pos_supervisor",
    status: "Activo",
  },
  {
    id: "user_manuel_soto",
    organizationId: SERGIO_ORG_ID,
    name: "Manuel Soto",
    email: "m.soto@horizonte.cl",
    role: "Lector",
    cargoId: "pos_maestro_primera",
    status: "Activo",
  },
];

export const SERGIO_CONSTRUCTION_ORG_STRUCTURE: OrgStructureData = {
  workCenters: SERGIO_WORK_CENTERS,
  areas: SERGIO_AREAS,
  positions: SERGIO_POSITIONS,
  users: SERGIO_USERS,
  lastUpdated: "2026-02-20T10:00:00.000Z",
};

// ============================================================================
// MATRICES IPER PARA SERGIO (1 BORRADOR, 1 EN REVISIÓN, 1 VIGENTE CON IRL)
// ============================================================================
export const SERGIO_IPER_MATRICES: IperMatrixItem[] = [
  // 1. Matriz en Borrador
  {
    id: "org_sergio_m-borrador-excavaciones",
    code: "M-EXC-01",
    name: "Matriz de Excavaciones - Obra Hospital Regional Biobío",
    workCenter: "Obra Hospital Regional Biobío",
    workCenterId: "wc_biobio_hospital",
    workCenterName: "Obra Hospital Regional Biobío",
    areaId: "area_hb_civiles",
    areaName: "Obras Civiles",
    processId: "pr_hb_civ_1",
    processName: "Excavaciones Masivas y Zanjas",
    responsible: "Camila Valenzuela (Prevención)",
    lastReviewDate: "2026-02-18",
    expiryText: "En elaboración inicial",
    totalRecords: 2,
    intolerableRisks: 1,
    status: "Borrador",
    evaluations: [
      {
        id: "ev-exc-1",
        process: "Excavaciones Masivas y Zanjas",
        task: "Apertura mecánica de zanjas profundas para fundaciones",
        hazard: "Derrumbe de terreno y colapso de paredes de excavación",
        riskEvent: "Atrapamiento por desprendimiento de tierra",
        probInitial: 4,
        sevInitial: 4,
        riskInitial: 16,
        initialLevel: "Crítico",
        controls: "Instalación de entibaciones de acero según NCh 349 y taludes en 45°",
        probResidual: 2,
        sevResidual: 4,
        riskResidual: 8,
        residualLevel: "Alto",
        controlStatus: "En proceso",
        responsible: "Camila Valenzuela (Prevención)",
        cargo: "Jornal, Operador de Maquinaria",
        area: "Obras Civiles",
        workCenter: "Obra Hospital Regional Biobío",
      },
      {
        id: "ev-exc-2",
        process: "Excavaciones Masivas y Zanjas",
        task: "Maniobras de retroexcavadora en borde de talud",
        hazard: "Terreno inestable y proximidad al borde de excavación",
        riskEvent: "Volcamiento de maquinaria pesada al foso",
        probInitial: 3,
        sevInitial: 4,
        riskInitial: 12,
        initialLevel: "Alto",
        controls: "Delimitación con New Jersey a 2.5m de distancia y señalero permanente con paleta",
        probResidual: 1,
        sevResidual: 4,
        riskResidual: 4,
        residualLevel: "Medio",
        controlStatus: "En proceso",
        responsible: "Camila Valenzuela (Prevención)",
        cargo: "Operador de Maquinaria",
        area: "Obras Civiles",
        workCenter: "Obra Hospital Regional Biobío",
      },
    ],
  },

  // 2. Matriz en Revisión
  {
    id: "org_sergio_m-revision-montaje",
    code: "M-MNT-02",
    name: "Matriz de Montaje Estructural - Obra Edificio Corporativo Santiago",
    workCenter: "Obra Edificio Corporativo Santiago",
    workCenterId: "wc_santiago_corp",
    workCenterName: "Obra Edificio Corporativo Santiago",
    areaId: "area_cs_construccion",
    areaName: "Construcción",
    processId: "pr_cs_cst_5",
    processName: "Montaje Estructural a Mayor a 1.8m",
    responsible: "Rodrigo Morales (Jefe de Terreno)",
    lastReviewDate: "2026-02-22",
    expiryText: "Pendiente firma Gerencia Técnica",
    totalRecords: 3,
    intolerableRisks: 1,
    status: "En revisión",
    evaluations: [
      {
        id: "ev-mnt-1",
        process: "Montaje Estructural a Mayor a 1.8m",
        task: "Posicionamiento de vigas metálicas en altura superior a 15m",
        hazard: "Trabajo en altura física sobre vigas sin plataforma continua",
        riskEvent: "Caída a distinto nivel con consecuencias graves o fatales",
        probInitial: 4,
        sevInitial: 4,
        riskInitial: 16,
        initialLevel: "Crítico",
        controls: "Uso obligatorio de arnés con doble cabo de vida enganchado a línea de acero certificada",
        probResidual: 2,
        sevResidual: 3,
        riskResidual: 6,
        residualLevel: "Medio",
        controlStatus: "En proceso",
        responsible: "Rodrigo Morales (Jefe de Terreno)",
        cargo: "Maestro Primera, Capataz",
        area: "Construcción",
        workCenter: "Obra Edificio Corporativo Santiago",
      },
      {
        id: "ev-mnt-2",
        process: "Montaje Estructural a Mayor a 1.8m",
        task: "Izaje con grúa torre de perfiles pesados de acero",
        hazard: "Carga pesada suspendida y rotura potencial de eslingas",
        riskEvent: "Golpe o aplastamiento por desprendimiento de carga",
        probInitial: 3,
        sevInitial: 4,
        riskInitial: 12,
        initialLevel: "Alto",
        controls: "Zona de exclusión perimetral con conos y verificación de código de colores mensual en eslingas",
        probResidual: 1,
        sevResidual: 4,
        riskResidual: 4,
        residualLevel: "Medio",
        controlStatus: "Implementado",
        responsible: "Rodrigo Morales (Jefe de Terreno)",
        cargo: "Jornal, Supervisor",
        area: "Construcción",
        workCenter: "Obra Edificio Corporativo Santiago",
      },
      {
        id: "ev-mnt-3",
        process: "Montaje Estructural a Mayor a 1.8m",
        task: "Soldadura al arco de uniones estructurales en altura",
        hazard: "Proyección de chispas y partículas incandescentes",
        riskEvent: "Quemaduras en piel y amago de incendio en niveles inferiores",
        probInitial: 3,
        sevInitial: 3,
        riskInitial: 9,
        initialLevel: "Medio",
        controls: "Mantas ignífugas bajo punto de soldadura y extintor PQS de 10 kg disponible en plataforma",
        probResidual: 1,
        sevResidual: 2,
        riskResidual: 2,
        residualLevel: "Bajo",
        controlStatus: "Implementado",
        responsible: "Rodrigo Morales (Jefe de Terreno)",
        cargo: "Maestro Primera",
        area: "Construcción",
        workCenter: "Obra Edificio Corporativo Santiago",
      },
    ],
  },

  // 3. Matriz Vigente (Permite generar IRL por Cargo)
  {
    id: "org_sergio_m-vigente-construccion",
    code: "M-CST-03",
    name: "Matriz de Construcción - Obra Condominio Parque Norte",
    workCenter: "Obra Condominio Parque Norte",
    workCenterId: "wc_parque_norte",
    workCenterName: "Obra Condominio Parque Norte",
    areaId: "area_pn_terminaciones",
    areaName: "Terminaciones",
    processId: "pr_pn_ter_1",
    processName: "Pintura de Interiores y Fachadas",
    responsible: "Sergio Jara (Administrador de Obra)",
    lastReviewDate: "2026-02-15",
    expiryText: "Vigente hasta Febrero 2027",
    totalRecords: 6,
    intolerableRisks: 0,
    status: "Vigente",
    evaluations: [
      {
        id: "ev-cst-1",
        process: "Pintura de Interiores y Fachadas",
        task: "Preparación y lijado de muros en andamios modulares",
        hazard: "Superficie de trabajo en altura y piso resbaladizo o desordenado",
        riskEvent: "Caída al mismo nivel y caída a distinto nivel en andamio",
        probInitial: 3,
        sevInitial: 3,
        riskInitial: 9,
        initialLevel: "Medio",
        controls: "Andamios certificados con barandas dobles, rodapiés afianzados y orden permanente de cables",
        probResidual: 1,
        sevResidual: 2,
        riskResidual: 2,
        residualLevel: "Bajo",
        controlStatus: "Implementado",
        responsible: "Sergio Jara",
        cargo: "Maestro Primera",
        area: "Terminaciones",
        workCenter: "Obra Condominio Parque Norte",
      },
      {
        id: "ev-cst-2",
        process: "Pintura de Interiores y Fachadas",
        task: "Corte y desbaste de perfiles metálicos de terminación con amoladora",
        hazard: "Disco abrasivo a 11.000 RPM sin protección o mal fijado",
        riskEvent: "Golpeado por herramientas y proyección de partículas a ojos y rostro",
        probInitial: 3,
        sevInitial: 3,
        riskInitial: 9,
        initialLevel: "Medio",
        controls: "Carcasa protectora fija, antiparras de policarbonato con protección lateral y careta facial",
        probResidual: 1,
        sevResidual: 2,
        riskResidual: 2,
        residualLevel: "Bajo",
        controlStatus: "Implementado",
        responsible: "Sergio Jara",
        cargo: "Maestro Primera",
        area: "Terminaciones",
        workCenter: "Obra Condominio Parque Norte",
      },
      {
        id: "ev-cst-3",
        process: "Pintura de Interiores y Fachadas",
        task: "Acarreo y levantamiento manual de tinas de pasta y pintura de 25 kg",
        hazard: "Manipulación manual de cargas pesadas por encima del límite legal",
        riskEvent: "Sobreesfuerzo físico y lumbago ocupacional (Ley 20.949)",
        probInitial: 3,
        sevInitial: 2,
        riskInitial: 6,
        initialLevel: "Medio",
        controls: "Uso obligatorio de transpaleta manual y ayuda de segundo operario para bultos > 25 kg",
        probResidual: 1,
        sevResidual: 1,
        riskResidual: 1,
        residualLevel: "Bajo",
        controlStatus: "Implementado",
        responsible: "Sergio Jara",
        cargo: "Maestro Primera",
        area: "Terminaciones",
        workCenter: "Obra Condominio Parque Norte",
      },
      {
        id: "ev-cst-4",
        process: "Pintura de Interiores y Fachadas",
        task: "Aplicación de pintura esmalte y selladores base solvente en recintos cerrados",
        hazard: "Concentración de vapores orgánicos volátiles en recintos con poca ventilación",
        riskEvent: "Exposición e inhalación de sustancias químicas según DS 594",
        probInitial: 3,
        sevInitial: 3,
        riskInitial: 9,
        initialLevel: "Medio",
        controls: "Ventilación mecánica forzada con extractor axial y respirador con filtro 3M 6001 para vapores orgánicos",
        probResidual: 1,
        sevResidual: 2,
        riskResidual: 2,
        residualLevel: "Bajo",
        controlStatus: "Implementado",
        responsible: "Sergio Jara",
        cargo: "Maestro Primera",
        area: "Terminaciones",
        workCenter: "Obra Condominio Parque Norte",
      },
      {
        id: "ev-cst-5",
        process: "Pintura de Interiores y Fachadas",
        task: "Conexión de extensiones y focos halógenos para cuadrillas de pintura",
        hazard: "Cables eléctricos con aislamiento deteriorado y presencia de humedad",
        riskEvent: "Contacto con energía eléctrica directa o indirecta",
        probInitial: 3,
        sevInitial: 4,
        riskInitial: 12,
        initialLevel: "Alto",
        controls: "Disyuntores diferenciales de alta sensibilidad de 30mA y cables aéreos con ganchos aislados",
        probResidual: 1,
        sevResidual: 3,
        riskResidual: 3,
        residualLevel: "Bajo",
        controlStatus: "Implementado",
        responsible: "Sergio Jara",
        cargo: "Electricista",
        area: "Terminaciones",
        workCenter: "Obra Condominio Parque Norte",
      },
      {
        id: "ev-cst-6",
        process: "Pintura de Interiores y Fachadas",
        task: "Limpieza y despeje continuo de despuntes y escombros en pisos de departamentos",
        hazard: "Clavos salientes, despuntes de madera y polvo en suspensión",
        riskEvent: "Pinchazos en planta de pie, tropiezos y proyección de polvo",
        probInitial: 3,
        sevInitial: 2,
        riskInitial: 6,
        initialLevel: "Medio",
        controls: "Calzado de seguridad con plantilla de acero anticlavo y doblado inmediato de clavos",
        probResidual: 1,
        sevResidual: 1,
        riskResidual: 1,
        residualLevel: "Bajo",
        controlStatus: "Implementado",
        responsible: "Sergio Jara",
        cargo: "Jornal",
        area: "Terminaciones",
        workCenter: "Obra Condominio Parque Norte",
      },
    ],
  },
];

// ============================================================================
// PROGRAMA ANUAL DE TRABAJO PREVENTIVO (12 ACTIVIDADES COMPLETAS)
// ============================================================================
export const SERGIO_PREVENTIVE_ACTIVITIES: ProgramActivity[] = [
  {
    id: "act-sergio-01",
    code: "PLN-01",
    name: "Elaboración y Aprobación del Programa Anual de Seguridad y Salud 2026",
    description: "Definición de objetivos, metas cuantitativas, presupuesto y cronograma anual de prevención para las 3 obras.",
    objective: "Establecer la directriz de seguridad de Constructora Horizonte SpA ante la gerencia y mutualidad.",
    category: "Planificación y Gestión",
    startDate: "2026-01-05",
    endDate: "2026-01-20",
    periodicity: "Anual",
    applicability: "Base",
    status: "Cumplida",
    progress: 100,
    responsibleUserName: "Sergio Jara",
    areaName: "Administración de Obra",
    evidences: [
      {
        id: "ev-p-1",
        name: "Aprobacion_Programa_Anual_Horizonte_2026.pdf",
        type: "Documento",
        uploadedAt: "2026-01-19",
        fileSize: "2.4 MB",
      },
    ],
    observations: "Aprobado por Gerente General y Departamentos de Prevención.",
  },
  {
    id: "act-sergio-02",
    code: "IPER-01",
    name: "Revisión y Actualización de Matrices IPER en Edificio Corporativo y Obras Civiles",
    description: "Evaluación de peligros y jerarquía de controles para procesos críticos de excavaciones, enfierradura y montaje.",
    objective: "Mantener matrices al día según exigencias del DS 44.",
    category: "Gestión de Riesgos",
    startDate: "2026-01-20",
    endDate: "2026-02-15",
    periodicity: "Semestral",
    applicability: "Base",
    status: "Cumplida",
    progress: 100,
    responsibleUserName: "Camila Valenzuela",
    areaName: "Prevención de Riesgos",
    evidences: [
      {
        id: "ev-p-2",
        name: "Informe_Actualizacion_IPER_2026.pdf",
        type: "Documento",
        uploadedAt: "2026-02-14",
        fileSize: "3.1 MB",
      },
    ],
  },
  {
    id: "act-sergio-03",
    code: "IRL-01",
    name: "Generación y Difusión de Fichas de Identificación de Riesgos Laborales (IRL)",
    description: "Emisión de fichas IRL específicas para Maestro Primera, Electricista, Jornal y Operador de Maquinaria.",
    objective: "Asegurar que cada trabajador conozca sus riesgos y medidas de control obligatorias.",
    category: "Información de Riesgos Laborales (IRL)",
    startDate: "2026-02-10",
    endDate: "2026-02-28",
    periodicity: "Trimestral",
    applicability: "Base",
    status: "Cumplida",
    progress: 100,
    responsibleUserName: "Camila Valenzuela",
    areaName: "Prevención de Riesgos",
    evidences: [
      {
        id: "ev-p-3",
        name: "Registro_Entrega_IRL_Cuadrillas_Febrero.pdf",
        type: "Documento",
        uploadedAt: "2026-02-26",
        fileSize: "1.9 MB",
      },
    ],
  },
  {
    id: "act-sergio-04",
    code: "CAP-01",
    name: "Capacitación Práctica: Trabajo Seguro en Altura Física y Revisión de SPDC",
    description: "Taller teórico-práctico de inspección de arneses, líneas de vida y cálculo de distancia libre de caída.",
    objective: "Prevenir incidentes por caída a distinto nivel en montaje estructural.",
    category: "Capacitación y Difusión",
    startDate: "2026-03-05",
    endDate: "2026-03-20",
    periodicity: "Mensual",
    applicability: "Base",
    status: "Cumplida",
    progress: 100,
    responsibleUserName: "Rodrigo Morales",
    areaName: "Construcción",
    evidences: [
      {
        id: "ev-p-4",
        name: "Certificados_Asistencia_Altura_Marzo.pdf",
        type: "Documento",
        uploadedAt: "2026-03-19",
        fileSize: "4.2 MB",
      },
    ],
  },
  {
    id: "act-sergio-05",
    code: "CAP-02",
    name: "Capacitación Ergonómica: Manejo Manual de Carga y Aplicación Ley 20.949",
    description: "Instrucción de técnicas de levantamiento y uso obligatorio de ayudas mecánicas en faena.",
    objective: "Reducir licencias por sobreesfuerzo y trastornos musculoesqueléticos.",
    category: "Capacitación y Difusión",
    startDate: "2026-04-01",
    endDate: "2026-04-20",
    periodicity: "Bimestral",
    applicability: "Base",
    status: "Cumplida",
    progress: 100,
    responsibleUserName: "Camila Valenzuela",
    areaName: "Prevención de Riesgos",
    evidences: [],
  },
  {
    id: "act-sergio-06",
    code: "INSP-01",
    name: "Inspección Cruzada de Andamios, Escalas y Plataformas Provisorias",
    description: "Revisión técnica de arriostramiento, rodapiés, barandas dobles y bases niveladoras según NCh 998.",
    objective: "Garantizar estándar 100% operativo en andamios de las 3 obras.",
    category: "Inspecciones y Observaciones",
    startDate: "2026-05-02",
    endDate: "2026-05-25",
    periodicity: "Mensual",
    applicability: "Base",
    status: "Cumplida",
    progress: 100,
    responsibleUserName: "Patricio Fuenzalida",
    areaName: "Construcción",
    evidences: [],
  },
  {
    id: "act-sergio-07",
    code: "EMERG-01",
    name: "Simulacro de Evacuación por Conato de Incendio y Sismo Mayor",
    description: "Ejercicio de evacuación total de pisos superiores hacia zona de seguridad en faena.",
    objective: "Comprobar tiempos de respuesta y preparación de brigadistas de obra.",
    category: "Emergencias y Simulacros",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    periodicity: "Semestral",
    applicability: "Base",
    status: "En curso",
    progress: 60,
    responsibleUserName: "Camila Valenzuela",
    areaName: "Prevención de Riesgos",
    evidences: [],
  },
  {
    id: "act-sergio-08",
    code: "EPP-01",
    name: "Auditoría de Terreno y Recambio Programado de Elementos de Protección Personal",
    description: "Inspección de cascos con barbiquejo, calzado de seguridad, antiparras y filtros de polvo/químicos.",
    objective: "Asegurar estado óptimo de EPP en el 100% de la dotación.",
    category: "Inspecciones y Observaciones",
    startDate: "2026-07-01",
    endDate: "2026-07-28",
    periodicity: "Mensual",
    applicability: "Base",
    status: "En curso",
    progress: 40,
    responsibleUserName: "Patricio Fuenzalida",
    areaName: "Bodega y Logística",
    evidences: [],
  },
  {
    id: "act-sergio-09",
    code: "CPHS-01",
    name: "Reunión Ordinaria Mensual y Seguimiento de Acuerdos del Comité Paritario (CPHS)",
    description: "Sesión de trabajo mensual de CPHS Faena y revisión de libro de actas.",
    objective: "Cumplimiento del DS 54 y fomento a la participación de trabajadores.",
    category: "Participación y CPHS",
    startDate: "2026-08-05",
    endDate: "2026-08-25",
    periodicity: "Mensual",
    applicability: "Base",
    status: "Pendiente",
    progress: 0,
    responsibleUserName: "Sergio Jara",
    areaName: "Administración de Obra",
    evidences: [],
  },
  {
    id: "act-sergio-10",
    code: "PROTO-01",
    name: "Monitoreo y Dosimetrías de Ruido (PREXOR) y Muestreo de Sílice (PLANESI)",
    description: "Campañas de medición ambiental en frentes de demolición, corte de hormigón y excavaciones.",
    objective: "Verificación de cumplimiento de límites permisibles según DS 594.",
    category: "Protocolos Minsal",
    startDate: "2026-09-01",
    endDate: "2026-09-30",
    periodicity: "Anual",
    applicability: "Base",
    status: "Pendiente",
    progress: 0,
    responsibleUserName: "Camila Valenzuela",
    areaName: "Prevención de Riesgos",
    evidences: [],
  },
  {
    id: "act-sergio-11",
    code: "AUD-01",
    name: "Auditoría Interna Anual del Sistema de Gestión y Cumplimiento Legal DS 44",
    description: "Evaluación integral de cumplimiento de los 10 requisitos normativos del DS 44.",
    objective: "Detectar no conformidades antes del cierre de ciclo fiscal y auditoría de mutualidad.",
    category: "Cierre y Evaluación Anual",
    startDate: "2026-10-10",
    endDate: "2026-11-15",
    periodicity: "Anual",
    applicability: "Base",
    status: "Pendiente",
    progress: 0,
    responsibleUserName: "Sergio Jara",
    areaName: "Administración de Obra",
    evidences: [],
  },
  {
    id: "act-sergio-12",
    code: "EVAL-01",
    name: "Evaluación Anual de Desempeño Preventivo y Presentación a Directorio",
    description: "Cálculo de tasas de accidentabilidad, frecuencia, gravedad y cierre formal del Programa 2026.",
    objective: "Reportar resultados y lecciones aprendidas a la Gerencia General.",
    category: "Cierre y Evaluación Anual",
    startDate: "2026-12-01",
    endDate: "2026-12-28",
    periodicity: "Anual",
    applicability: "Base",
    status: "Pendiente",
    progress: 0,
    responsibleUserName: "Sergio Jara",
    areaName: "Administración de Obra",
    evidences: [],
  },
];

/**
 * Función idempotente y segura para sembrar la base de datos de Supabase con el dataset
 * representativo de empresa constructora para la cuenta sergio.jara@safetyclub.cl (org_sergio).
 */
export async function seedSergioConstructionDemo(): Promise<{ success: boolean; message: string }> {
  const { getSupabaseClient } = await import("@/lib/supabaseClient");
  const client = getSupabaseClient();
  if (!client) {
    return { success: false, message: "Cliente de Supabase no disponible." };
  }

  try {
    // 1. Preferencias organizacionales con las 12 actividades anuales incluidas
    const prefsPayload = {
      ...SERGIO_CONSTRUCTION_PREFERENCES,
      preventiveActivities: SERGIO_PREVENTIVE_ACTIVITIES,
    };
    const { error: errPrefs } = await client.from("organization_preferences").upsert({
      id: SERGIO_ORG_ID,
      preferences: prefsPayload,
      updated_at: new Date().toISOString(),
    });
    if (errPrefs) throw errPrefs;

    // 2. Estructura Organizacional: 3 obras, áreas, procesos, subprocesos, 13 cargos y usuarios
    const { error: errStruct } = await client.from("org_structure").upsert([
      { id: `structure_${SERGIO_ORG_ID}`, areas: SERGIO_CONSTRUCTION_ORG_STRUCTURE, updated_at: new Date().toISOString() },
      { id: SERGIO_ORG_ID, areas: SERGIO_CONSTRUCTION_ORG_STRUCTURE, updated_at: new Date().toISOString() },
    ]);
    if (errStruct) throw errStruct;

    // 3. Matrices IPER (1 Borrador, 1 En revisión, 1 Vigente con IRL)
    const matrixRows = SERGIO_IPER_MATRICES.map((m) => {
      const anyM = m as any;
      return {
        id: m.id,
        code: m.code,
        title: m.name || m.title,
        area: anyM.areaName || anyM.area || "",
        work_center: anyM.workCenterName || anyM.workCenter || "",
        responsible: m.responsible,
        status: m.status,
        progress: typeof anyM.progress === "number" ? anyM.progress : 0,
        total_risks: typeof m.totalRecords === "number" ? m.totalRecords : 0,
        critical_risks: typeof m.intolerableRisks === "number" ? m.intolerableRisks : 0,
        last_review: m.lastReviewDate || null,
        next_review: m.expiryText || null,
        hazards: m.evaluations || [],
      };
    });
    const { error: errMatrices } = await client.from("iper_matrices").upsert(matrixRows);
    if (errMatrices) throw errMatrices;

    return { success: true, message: "Dataset de Constructora Sergio sembrado con éxito en Supabase." };
  } catch (e: any) {
    console.error("Error al sembrar dataset de Sergio:", e);
    return { success: false, message: e?.message || "Error desconocido al sembrar." };
  }
}

